---
- name: install facebook-sdk if facebook push is enabled
  become: yes
  pip:
    name: facebook-sdk
    executable: pip3
    state: present
  when: enable_facebook_push | bool

- name: drop template facebook facebook-sdk config file
  copy:
    src: facebook.conf
    dest: /home/pi/.facebook.conf
    force: no
    owner: pi
    group: pi
    mode: 0600
  when: enable_facebook_push | bool
...
