---
# dependent packages and libs to be installed
- include: dependencies.yml

# environment configuration files
- include: configs.yml

# ntp configurations
- include: ntp.yml

# core software modules
- include: sdr.yml

# tools and utilities
- include: tools.yml

# ramfs setup
- include: ramfs.yml

# email setup
- include: email.yml

# Twitter push setup
- include: twitter.yml

# Facebook push setup
- include: facebook.yml

# Instagram push setup
- include: instagram.yml
...
